# One hot encoding in tensorflow

In [1]:
import tensorflow as tf

2023-09-12 20:38:04.877086: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-12 20:38:04.878627: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-12 20:38:04.917518: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-12 20:38:04.918315: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-12 20:38:05.720979: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [3]:
list = [0,1,2]
tf.one_hot(list, depth=len(list))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

# if vector
### if axis == -1, shape = (feature x depth) 
### if axis == 0 , shape = (depth x feature)
default == -1


In [9]:
list = [0,1,2,3]
depth = 3 
tf.one_hot(list, depth, on_value= 5, off_value=0 )   # shape = feature x depth

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5],
       [0, 0, 0]], dtype=int32)>

In [11]:
tf.one_hot(list , depth = 3, axis= 0)   # shape = depth x feature

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

### for matrix ::
if axis = -1 , shape = (batch x features x depth)
if axis = 1 , shape = (batch x depth  x features)
if axis = 0 , shape = (depth x batch x features)

In [12]:
list = [[1,2], [3,4]]
depth  = 3
tf.one_hot(list, depth, axis = 0)      

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[1., 0.],
        [0., 0.]],

       [[0., 1.],
        [0., 0.]]], dtype=float32)>

In [13]:
tf.one_hot(list, depth, axis = 1)      

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[0., 0.],
        [1., 0.],
        [0., 1.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

In [14]:
tf.one_hot(list, depth, axis = -1)      

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 1., 0.],
        [0., 0., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [25]:
list = tf.ragged.constant([[0,1], [2]])
tf.one_hot(list , depth)

<tf.RaggedTensor [[[1.0, 0.0, 0.0],
  [0.0, 1.0, 0.0]], [[0.0, 0.0, 1.0]]]>