In [1]:
import tensorflow as tf

2023-08-30 21:55:18.971802: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-30 21:55:18.991958: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-30 21:55:19.170627: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-30 21:55:19.171639: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-30 21:55:20.226346: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [4]:
a = tf.constant([-2,-1,0,1,2], dtype= tf.float32)
b = tf.keras.activations.sigmoid(a)
b.numpy()

array([0.11920292, 0.26894143, 0.5       , 0.7310586 , 0.8807971 ],
      dtype=float32)

In [6]:
c = tf.keras.activations.relu(a)
c.numpy()

array([0., 0., 0., 1., 2.], dtype=float32)

In [8]:
c = tf.keras.activations.tanh(a)
c.numpy()

array([-0.9640276, -0.7615942,  0.       ,  0.7615942,  0.9640276],
      dtype=float32)

In [9]:
import numpy as np 

In [10]:
revenue = np.array([[100, 200, 120], [24,36,40], [12, 18, 20]])
expenses = np.array([[80, 90, 100], [10,16,20], [8, 19, 10]])

In [12]:
profit = revenue - expenses
profit

array([[ 20, 110,  20],
       [ 14,  20,  20],
       [  4,  -1,  10]])