In [1]:
def navie_relu(x) :
    assert len(x.shape) == 2
    x = x.copy()
    for i in range (x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] = max(x[i,j], 0)
    return x

broadcasting


In [5]:
import numpy as np 
x = np.random.random((64,3,32,10))
y = np.random.random((32,10))
z = np.maximum(x,y)
z

array([[[[0.92747555, 0.43368673, 0.97529443, ..., 0.737889  ,
          0.43803271, 0.40898321],
         [0.86075612, 0.65670196, 0.45850703, ..., 0.99180495,
          0.87412573, 0.78107871],
         [0.95909076, 0.40875567, 0.57264349, ..., 0.29782245,
          0.4020805 , 0.40516143],
         ...,
         [0.11029061, 0.36540929, 0.56149029, ..., 0.9413257 ,
          0.97640463, 0.28570888],
         [0.53718115, 0.89414966, 0.9106946 , ..., 0.74664672,
          0.8482789 , 0.37207521],
         [0.55381323, 0.52240673, 0.91253586, ..., 0.3442562 ,
          0.96139999, 0.76610474]],

        [[0.6366273 , 0.77767772, 0.97529443, ..., 0.07872507,
          0.92641366, 0.56671775],
         [0.72089485, 0.65670196, 0.72802542, ..., 0.53155599,
          0.99282254, 0.91615099],
         [0.95909076, 0.47626793, 0.47343022, ..., 0.16893287,
          0.4020805 , 0.90572495],
         ...,
         [0.66487786, 0.46646754, 0.60334107, ..., 0.84047115,
          0.98097146, 0.3

In [7]:
x.shape

(64, 3, 32, 10)

In [8]:
y.shape

(32, 10)

In [10]:
def ndot(x,y):
    assert len(x.shape) ==1
    assert len(y.shape) ==1
    assert x.shape[0] == y.shape[0]
    z = 0
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [20]:
x = np.array(range(9))
y = np.array(range(9))
z = ndot(x , y)
z

204

In [21]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8])